### ISSUE TITLE
Idea like Monitor, MQTT maybe

### ISSUE THREAD

**Issue by SaturnusDJ** [mueslo/openwrt_hass_devicetracker#31]
https://github.com/andrewjfreyer/monitor

It uses MQTT to send updated to HA about BT devices.
The interesting thing is that HA can ask Monitor to scan for updates. Similarly, if applied to openwrt_hass_devicetracker, we might define triggers in HA that will ask openwrt_hass_devicetracker to send out an update. For example on HA startup (Which is quite a pain point, because all WiFi devices will be marked as away because HA is stupid.) or 20 seconds after the front door was opened. 

I guess currently the only way to do this is with https://www.home-assistant.io/components/shell_command/ right?

**Comment by mueslo** [comment]
How would HomeAssistant then trigger the scan automatically?

**Comment by SaturnusDJ** [comment]
After event x/y/z send a MQTT message from HA to the router requesting an update of connected WiFi devices.

**Comment by SaturnusDJ** [comment]
In my case I restart the [monitor](https://github.com/andrewjfreyer/monitor) program/script 18 seconds after startup of HA:

```
- alias: System - Restart BT Monitor on startup
  trigger:
  - platform: homeassistant
    event: start
  action:
  - delay:
      seconds: 18
  - service: mqtt.publish
    data:
      topic: 'monitor/scan/restart'
```

In case of hass_tracker, another event could be after the OpenWRT device was away in HA ping/NMAP device tracker and 'came home again.' (Implicating a router restart.)
